### ISSUE TITLE
VRF API refactor

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/jellyfish#125]
There're a few things to follow-up on VRF refactoring:

- possible to remove `CSID` domain separator? (how necessary)
- should add the `output` to `vrf_verify(pk, input, output, proof)` API or follow this [IRTF draft](https://datatracker.ietf.org/doc/pdf/draft-irtf-cfrg-vrf-15) and leaving it out?
- should the `<H: Hasher>` be generic over `VrfScheme` or `VrfScheme::evaluate()`?

cc @chancharles92 @mrain @jbearer @DieracDelta @nyospe @philippecamacho

**Comment by DieracDelta** [comment]
A couple of other things:
- we may want to require some of the associated types of VRF implement: `Sync + Send + PartialEq + Clone + Serialize + for<'a> Deserialize<'a>`
- we need to expose a bytes representation of the keys so we aren't doing a cursed serialization [here](https://github.com/EspressoSystems/HotShot/blob/main/src/traits/election/vrf.rs#L204)

**Comment by nyospe** [comment]
Neither `VrfSchema` nor `VrfSchema::evaluate` should be generic over `H: Hasher`.

The use of a hasher is specific to some (many) implementations, but not an inherent property of a `VrfSchema`, and only the structs that implement `VrfSchema` with a hasher should be generic. `VrfSchema` should not be generic. `BLSVrfSchema` should be.
