### ISSUE TITLE
Ark-sponge compatibilty

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/jellyfish#15]
Currently we have rescue-based sponge construction whereas `ark-sponge` repo supports Poseidon. But it may be beneficial to be compliant to [their trait](https://github.com/arkworks-rs/sponge/blob/master/src/lib.rs#L108).

**Comment by zhenfeizhang** [comment]
working on #46, might as well get this done :-)

**Comment by zhenfeizhang** [comment]
while working on this, i realized that their interfaces is really not compatible with ours. They are designed to manipulate on bits as in the case of poseidon. we can fit there but we will be wasting a few (de)serializations.

I think we need to define a proper API ourselves, along the line of https://docs.rs/sha2/latest/sha2/trait.Digest.html

**Comment by zhenfeizhang** [comment]
> while working on this, i realized that their interfaces is really not compatible with ours. They are designed to manipulate on bits as in the case of poseidon. we can fit there but we will be wasting a few (de)serializations.
> 
> I think we need to define a proper API ourselves, along the line of https://docs.rs/sha2/latest/sha2/trait.Digest.html

Take it back. We can support those APIs
