### ISSUE TITLE
Pin the `espresso-systems-common` dependency to a particular revision

### ISSUE THREAD

**Issue by tessico** [EspressoSystems/jellyfish#155]
This is the only dependency in jellyfish that references the `main` branch. We should ideally pin it to a particular revision/tag. It might lead to builds failing, like now, when the common repo moves forward but jellyfish hasn't yet caught up. Thoughts?
@EspressoSystems/jellyfish @jbearer

**Comment by alxiong** [comment]
yes, we should pin a version. Let's add a tag to the latest commit on `espresso-systems-common` and pin to it?

**Comment by tessico** [comment]
Closed in https://github.com/EspressoSystems/jellyfish/pull/148
