### ISSUE TITLE
[API] Refactor `PRF` and `PrfGadget`

### ISSUE THREAD

**Issue by tessico** [EspressoSystems/jellyfish#160]
Our PRF mostly looks good.
It differs in API from [ark-crypto-primitives PRF](https://github.com/arkworks-rs/crypto-primitives/blob/main/src/prf/mod.rs), in that ours has a semi-stateful interface (input and output lengths are fixed per instance), while arkworks' PRF is fully stateless. I think it's ok to keep `self` in the `eval` function and have the length checks as they are currently.

One slight inconsistency I found though is the usage of `full_state_keyed_sponge`. Right now it does the padding itself (fill the input with zeros), and then calls `full_state_keyed_sponge_no_padding`.
Same for the circuit, with the caveat that the `padded` version doesn't even exist for the circuit.
Note that padding strategy is different to `sponge_with_padding`, which fills the remaining positions first with a `F::one()`, and only then with zeros.

Since the only user of `full_state_keyed_sponge_with_padding/full_state_keyed_sponge_no_padding` on `SpongePRF` is the `PRF`, I propose we: 
- fix the padding strategy of [`full_state_keyed_sponge_with_padding`](https://github.com/EspressoSystems/jellyfish/blob/9b7beb26360fb72eb80259330e37aa942e3bf854/primitives/src/rescue/sponge.rs#L83) to not append a `F::one()`, only zeros. Add a clear comment to explain the difference.
- have [`prf.eval`](https://github.com/EspressoSystems/jellyfish/blob/9b7beb26360fb72eb80259330e37aa942e3bf854/primitives/src/prf.rs#L88) not do the padding by itself, but rather use the 'fixed' `full_state_keyed_sponge_with_padding` method
- add the missing method `rescue_full_state_keyed_sponge_with_padding` on [`RescueGadget`](https://github.com/EspressoSystems/jellyfish/blob/9b7beb26360fb72eb80259330e37aa942e3bf854/primitives/src/circuit/rescue/native.rs#L188), which would follow the same padding strategy as `full_state_keyed_sponge_with_padding` and internally, once padded, calls `rescue_full_state_keyed_sponge_no_padding`
- rename [`PrfGadget`](https://github.com/EspressoSystems/jellyfish/blob/f74a6857bdbc2241e103e31f83af3b085d39f764/primitives/src/circuit/prf.rs#L17) to `PRFGadget`
- have `PRFGadget::eval_prf` call the new `rescue_full_state_keyed_sponge_with_padding` internally

**Comment by alxiong** [comment]
I think I'm gonna use generic const as I did for `struct FixedLengthRescueCRHF<F, INPUT_LEN, OUTPUT_LEN>` to make it more stateless and closer to the standard PRF def.
