### ISSUE TITLE
implement hash to group function

### ISSUE THREAD

**Issue by zhenfeizhang** [EspressoSystems/jellyfish#19]
We have not encountered a case where hash to group is necessary. So this is a low priority for now. 

We may consider implement 
- rejection sampling based, or
- Hash to Elliptic Curve implementation of <https://datatracker.ietf.org/doc/draft-irtf-cfrg-hash-to-curve/>

**Comment by alxiong** [comment]
now arkworks already have HashToCurve implementation, correct? should we close this? @zhenfeizhang

**Comment by mrain** [comment]
Shall we close this ticket and create a new one for constant time hash to bn254 curve?
cc @alxiong @chancharles92

**Comment by chancharles92** [comment]
@alxiong mentioned that arkworks v0.4 already has a hashtogroup implementation. Is it a naive one or something we can reuse?

**Comment by alxiong** [comment]
Yes, arkwork defined the [`trait HashToCurve` here](https://github.com/arkworks-rs/algebra/blob/13fd33e33c1186b2757e3fd3948b6eee16ee9e4b/ec/src/hashing/mod.rs#L9),  and implement it [here](https://github.com/arkworks-rs/algebra/blob/13fd33e33c1186b2757e3fd3948b6eee16ee9e4b/ec/src/hashing/map_to_curve_hasher.rs#L28) with flexibility for different hashing and mapping (from field to group) strategies.

I think we can close it for now. 

(ofc, if we want constant time in a separate issue/PR, consider building on top of [`subtle`](https://github.com/dalek-cryptography/subtle) or [`subtle-ng`](https://github.com/zkcrypto/subtle-ng))
