### ISSUE TITLE
Add `rust-version` to the manifest

### ISSUE THREAD

**Issue by tessico** [EspressoSystems/jellyfish#192]
Motivated by the discussion in https://github.com/EspressoSystems/jellyfish/pull/179.

I propose we set MSVR of jellyfish to 1.64:
- that's already two Rust releases behind and would have given users time to adopt the new release,
- our library is still WIP and breaking changes (incl. version support) are to be expected.

WDYT? @chancharles92 @alxiong @mrain @ggutoski

**Comment by alxiong** [comment]
concur! and like the idea and agree with the proposal.
