### ISSUE TITLE
Compress and Validation in Serialization

### ISSUE THREAD

**Issue by mrain** [EspressoSystems/jellyfish#213]
Currently the generic implementation of `CanonicalSerialize ` and `CanonicalDeserialize` ignore the `compress` and `validate` flags.
We should use them properly.

related commit: ([1](https://github.com/EspressoSystems/jellyfish/pull/207/commits/ad5a60a6ed2b31f6548b5dd2c798394f3dec4e4b), [2](https://github.com/EspressoSystems/jellyfish/pull/207/commits/04ccd513b231ab3ac165912b56e846bc39729f9d) ).

**Comment by mrain** [comment]
Affecting: [aead.rs](https://github.com/EspressoSystems/jellyfish/blob/main/primitives/src/aead.rs), [bls.rs](https://github.com/EspressoSystems/jellyfish/blob/main/primitives/src/signatures/bls.rs), [example.rs](https://github.com/EspressoSystems/jellyfish/blob/main/primitives/src/merkle_tree/examples.rs).

**Comment by tessico** [comment]
@mrain Just out of curiosity, do you already have in mind a design of how to go about this?

**Comment by mrain** [comment]
@tessico Discussed with @alxiong before. We thought that the only thing affected by this change is [here](https://github.com/EspressoSystems/tagged-base64/issues/49). We only need to update the macros for derived implementation of serde's serialization to incorporate the 2 new flags.
