### ISSUE TITLE
choosing u32 or u64 backends for x25519

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/jellyfish#258]
As part of work in #254, I choose `crypto_box = { version = "0.8.1", default-features = false, features = ["alloc", "u32_backend"] }` as default since we want to compiled down to wasm32 (for browser support)

Meanwhile, as requested by @mike1729, we should support choosing `u64_backend` as well. But as suggested in this comment: https://github.com/RustCrypto/nacl-compat/issues/85#issuecomment-1399502973, the best action now is to wait until `x25519-dalek` and `crypto_box`'s next release to completely remove these two feature flags, and configure using `cfg` (env var) from top level to avoid the additive feature flag problem.

**Comment by pmikolajczyk41** [comment]
do you have any estimates on when next `x25519-dalek` release will be ready/published?

**Comment by pmikolajczyk41** [comment]
if I'm not mistaken, their 4.0.0-rc.2 is already without these backend features

**Comment by alxiong** [comment]
you are right, @pmikolajczyk41  we can point to `crypto_box-v0.9.0-rc.0` right now it seems. (as seen [here](https://github.com/RustCrypto/nacl-compat/blob/crypto_box-v0.9.0-rc.0/crypto_box/Cargo.toml#L23))

I will create a quick PR for this.
