### ISSUE TITLE
Quality-of-life improvements for `multi_open_rou`

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/jellyfish#260]
Some quick and sloppy suggestions for the new `multi_open_rou` API.

- Eliminate the trait bound: https://github.com/EspressoSystems/jellyfish/blob/53403e2f33ca8b8cedb8733ccba3d300c4b4c613/primitives/src/pcs/mod.rs#L220-L221
- `multi_open_rou` does 2 things: evaluate and prove. Sometimes I want only one but not the other. Add 2 more methods `multi_open_rou_eval` and `multi_open_rou_prove`. Then `multi_open_rou` should just call these two methods.
  - How best to expose a `multi_open_rou_eval`? I could just do it myself with a `GeneralDensePolynomial` or you could provide a wrapper for me in `UnivariatePCS` so i don't need to use `GeneralDensePolynomial`.
- It's unfortunate that conversion to/from `GeneralDensePolynomial` requires copying coefficients. There ought to be a better way but I don't have any good suggestions atm.
- Need an `index_to_point` method.
- Need external access to FFT evaluation domain to ensure that RS decoding can use the same FFT domain. Perhaps we should expose this domain as an associated type of `UnivariatePCS` trait?
- maybe throw a useful error here instead of panicking? https://github.com/EspressoSystems/jellyfish/blob/53403e2f33ca8b8cedb8733ccba3d300c4b4c613/primitives/src/pcs/univariate_kzg/srs.rs#LL90C7-L90C7
  - better yet, throw it [here](https://github.com/EspressoSystems/jellyfish/blob/53403e2f33ca8b8cedb8733ccba3d300c4b4c613/primitives/src/pcs/mod.rs#L237) because this is more likely to be a point of confusion.
  - also, the srs now needs to support degree as large as the _number of points you want_ and not just the degree of the polynomial!!! This is a change of behaviour.
  - expose [this function](https://github.com/EspressoSystems/jellyfish/blob/53403e2f33ca8b8cedb8733ccba3d300c4b4c613/primitives/src/pcs/mod.rs#LL253C46-L253C46) for downstream users.
- Allow `num_points` argument to be much larger than the degree.

**Comment by alxiong** [comment]
With #265, most requests above are addressed, further note that:

> GeneralDensePolynomial requires copying coefficients

This is hard to avoid atm, FFT api from arkwork upstream accept a slice `domain.fft(coeffs: &[F])`, and in our case, we need to resize the `coeffs`, thus gaining ownership is inevitable (a slice of references `&[&F]` would also involve constructing a new vector of references, which won't be noticeably better). 

> Need an index_to_point method.

Now with `multi_open_rou_eval_domain() -> Radix2EvalDomain`, you could use [`domain.elements()`](https://docs.rs/ark-poly/latest/ark_poly/domain/trait.EvaluationDomain.html#tymethod.elements) as you can see in the test to access an iterator for all the roots, and use [`domain.element(index)`](https://docs.rs/ark-poly/latest/ark_poly/domain/trait.EvaluationDomain.html#method.element) to achieve `index_to_point` (alternatively, you could get all roots and indexing into it)

> expose [this function](https://github.com/EspressoSystems/jellyfish/blob/53403e2f33ca8b8cedb8733ccba3d300c4b4c613/primitives/src/pcs/mod.rs#LL253C46-L253C46) for downstream users

I believe we don't need to expose this with our refactored API now, can you double confirm? @ggutoski
