### ISSUE TITLE
bytes_to_field_elements should accept and return an iterator

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/jellyfish#300]
# Problem

_Originally posted by @ggutoski in https://github.com/EspressoSystems/jellyfish/pull/299#discussion_r1220149576_

Currently `bytes_to_field_elements` takes `AsRef<[u8]>` as input and returns `Vec<F>` as output. This can lead to unnecessary mem copy or heap alloc if the caller doesn't already have a `AsRef<[u8]>` or wants the output in some form other than `Vec<F>`.

Example: here the caller actually wants a `Vec<Vec<F>>`, and needs to copy/allocate a whole 2D vec for this purpose.

https://github.com/EspressoSystems/hotshot-primitives/blob/52b2f713eea897778eb8a73f401c9b1b4a2dde19/src/vid/advz.rs#L158-L159

# Solution

`bytes_to_field_elements` should accept `IntoIterator` instead of `AsRef<[u8]>` and should return an iterator over `F` instead of `Vec<F>`.

We should do the same for `bytes_from_field_elements`, though that will be more complicated to implement.

This solution is an example of the *iterator adaptor* pattern:
- [Processing a Series of Items with Iterators - The Rust Programming Language](https://doc.rust-lang.org/book/ch13-02-iterators.html#methods-that-produce-other-iterators)
- [std::iter - Rust](https://doc.rust-lang.org/stable/std/iter/index.html#adapters)

**Comment by amit0365** [comment]
Hello I am planning to work on this. Are you close to implementing the solution @ggutoski ?

**Comment by ggutoski** [comment]
> Hello I am planning to work on this. Are you close to implementing the solution @ggutoski ?

Hello @amit0365 . I have spent no time on this issue. Feel free to work on it! ❤️
