### ISSUE TITLE
Update Jellyfish to use `curve25519-dalek` version `4.0`

### ISSUE THREAD

**Issue by elliedavidson** [EspressoSystems/jellyfish#363]
This will allow it to be compatible with libp2p's usage of the library: https://github.com/mcginty/snow/releases/tag/v0.9.3

**Comment by ggutoski** [comment]
Problem solved and I didn't even do anything. As of today my local `Cargo.lock` specifies
```toml
[[package]]
name = "curve25519-dalek"
version = "4.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "f711ade317dd348950a9910f81c5947e3d8907ebd2b83f76203ff1807e6a2bc2"
dependencies = [
 "cfg-if",
 "cpufeatures",
 "curve25519-dalek-derive",
 "fiat-crypto",
 "platforms",
 "rustc_version",
 "subtle",
 "zeroize",
]
```

**Comment by mrain** [comment]
This needs to be solved by updating dependency `crypto_kx` to version `0.2.1`.
See todo here: https://github.com/EspressoSystems/jellyfish/blob/1403e7687ae9318ff556cde335c5009ee5645da7/primitives/Cargo.toml#L33C1-L34C1

I'll do it.
