### ISSUE TITLE
ADVZ allow large polynomial degree

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/jellyfish#393]
Premise: low polynomial degree is suboptimal. Performance might improve if we allow polynomials with larger degree. Thus, we need to send multiple evaluations (instead of only one evaluation) from each polynomial to each storage node.

**Comment by chancharles92** [comment]
My (unreliable) guess is that we can achieve the best performance when we set poly degree ~1000 and add parallelism (for doing k RS encoding/poly committing in parallel, where k is the number of polys).

**Comment by ggutoski** [comment]
As a bonus, a fix for this issue also fixes #356 . ie. it reduces the size of `Common`.
