### ISSUE TITLE
Integrate with ICICLE MSM

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/jellyfish#490]
As our exploration in #470, the benchmark on icicle is impressive on GPU, this issue aims to integrate into Jellyfish for MSM, NTT and potentially EC-NTT.

Here's an attentive plan:

- [x] setup separate nix devShell with cuda and other deps installed
- [x] workflow diagram (@mrain)
- [x] add optional invocation of icicle's MSM in `UnivariateKZG::commit()` behind a feature flag
- [x] add (equivalence) tests on MSM
- [x] add new benchmark for MSM alone
- [ ] add new benchmark for VID dispersal

**Comment by mrain** [comment]
Please check if it's clear enough: https://drive.google.com/file/d/1iPDYrTxI2EjBf_Ua4CoQklOJInTdgCED/view?usp=sharing

cc @alxiong @chancharles92

**Comment by philippecamacho** [comment]
Draft PR https://github.com/EspressoSystems/jellyfish/pull/498

**Comment by mrain** [comment]
Plan: 
- Merge PR #498 by Mar 6
- Integrate with VID by Mar 8.
- @mrain will help on integration with HotShot by Mar 15.

**Comment by mrain** [comment]
There're some troubles for upstream users now. In order to use GPU, you need to specify the icicle equivalent curves and fields. But if we move the icicle type generic to an associate type, it could be much easier.
```rust
pub trait GPUCommit<E, C>
```
to 
```rust
pub trait GPUCommit<E> {
    type ICICLE_EQUIV;
}
```

**Comment by mrain** [comment]
Because of the messy trait bounds, we are expecting a delay for this project.

updated timeline:

- refactor traits by Mar 13.
- VID integration by Mar 15.
- HotShot integration by Mar 20.
