### ISSUE TITLE
GPU accelerated VID disperse

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/jellyfish#521]
As a follow-up to #498 and part of overall VID optimization effort #358, we try to integrate the GPU-accelerated MSM into VID workflow.

**Comment by mrain** [comment]
wait a sec. we are missing impls for [`PayloadProver`](https://github.com/EspressoSystems/jellyfish/blob/main/primitives/src/vid/advz/payload_prover.rs) and [`Precomputable`](https://github.com/EspressoSystems/jellyfish/blob/main/primitives/src/vid/precomputable.rs) for `AdvzGPU`

**Comment by alxiong** [comment]
ah! apologize for missing them, are they necessary for HotShot integration? the annoyance is requiring breaking changes on these traits. namely using `&mut self` 

and possibly change back when we later update to later release of ICICLE.
