### ISSUE TITLE
A multiplicity different than expected can cause nodes to panic. 

### ISSUE THREAD

**Issue by elliedavidson** [EspressoSystems/jellyfish#644]
This issue was observed on version 0.4.5

Nodes will panic if they attempt to verify a VID share with a different multiplicity than the node expects.  An incorrectly configured node could cause many other network nodes to crash.  

To reproduce: 
* Run 1 HotShot leader with multiplicity = 2
* Run other HotShot nodes with multiplicity = 4
* Replica nodes will panic in the `verifiy_share` function in `vid/src/advz.rs`

**Comment by elliedavidson** [comment]
This issue actually needs to be in HotShot: https://github.com/EspressoSystems/HotShot/issues/3523

**Comment by ggutoski** [comment]
jellyfish should not panic for that. re-opening this issue. Thanks for posting!
