### ISSUE TITLE
Fix large shares when small payload and large multiplicity

### ISSUE THREAD

**Issue by akonring** [EspressoSystems/jellyfish#663]
In many settings it may be advantageous to configure the VID scheme to use large multiplicity.
However, the current implementation of the ADVZ scheme will force polynomials to be of size `multiplicity * recovery_threshold` even for small payloads.
Instead, the `disperse` function should use the lowest value for `multiplicity` such that `payload_len` $$\leq$$ `multiplicity * recovery_threshold`.

**Comment by ggutoski** [comment]
There are lots of ways to solve this problem, but all of them are bad ergonomics. After some discussion we decided the least bad solution is what's suggested by OP: silently use the smallest multiplicity needed to fit the entire payload into a single polynomial. We'll rename `multiplicity` -> `max_multiplicity` and update docs to explain that this arg allows the caller to specify only the *maximum* multiplicity that can be used for dispersal.
