### ISSUE TITLE
extract turbo plonk

### ISSUE THREAD

**Issue by zhenfeizhang** [EspressoSystems/jellyfish#67]
Created a [dedicated branch](https://github.com/EspressoSystems/jellyfish/tree/turbo-plonk) for turbo plonk. Let's work on this branch by submitting PRs against it (like what we did for plonk verifier).

- [x] #69
- [x] ~refactoring the code with better modularity~  
  - ~shall we allow for operators overloading?~ (future work)
- [x] ~gitbook~
- [x] #71 
- [x] Generate SRS, PK, VK for large enough circuit and version-control their sumcheck files in this repo while uploading the actual binary file to some AWS S3 bucket. (@zhenfeizhang)

**Comment by alxiong** [comment]
@zhenfeizhang  We are done with this I believe? Let's close this?

**Comment by zhenfeizhang** [comment]
Yes. Almost. I am uploading VKs etc. as suggested by Mat

**Comment by zhenfeizhang** [comment]
done in https://github.com/EspressoSystems/jellyfish/releases/tag/zprize
