### ISSUE TITLE
Remove derived implementations for private key types

### ISSUE THREAD

**Issue by mrain** [EspressoSystems/jellyfish#694]
Zulip discussion thread: https://espresso.zulipchat.com/#narrow/channel/311646-Consensus/topic/private.20keys/near/478545916

Summary: remove derived `Serialize`, `Debug` and `Display` for private key types.
Implement `Debug` for them but only print `***` or `<private key>` or something similar.

**Comment by alxiong** [comment]
we should also add `from/to_bytes()` on private keys.
