### ISSUE TITLE
[Constraints]: Comparison gate

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/jellyfish#81]
Add `lt`, `gt` gates to the constraint system. 

Reference: `r1cs-std`'s [`cmp.rs`](https://github.com/arkworks-rs/r1cs-std/blob/master/src/fields/fp/cmp.rs)

**Comment by alxiong** [comment]
Note: we use `range_check(a, bit_len) -> Vec<BoolVar>` that ensure variable `a \in [0, 2^bit_len)` and return the binary representation of `a` as a building block, this gate costs (`bit_len` boolean constraint + `bit_len / 3` linear combination) constraints 
(see "Range check" section in cap-spec for details, or [code here](https://github.com/EspressoSystems/jellyfish/blob/main/plonk/src/circuit/customized/mod.rs#L680-L684)). 

iiuc, arkworks' [`cmp.rs` constraint](https://github.com/arkworks-rs/r1cs-std/blob/master/src/fields/fp/cmp.rs) logic for checking `a<b` goes as follows: 
1. check MSB of `a` and `b` is `0`, by checking `a<(p-1)/2 && b<(p-1)/2` -- takes 2 `range_check`
2. compute `c = (a-b)*2` in circuit, and decompose into binary representation and return the MSB of `c` -- takes 1 subtraction gate and a `range_check` gate

the constraint works because if `a<b`, then after subtraction, the MSB would be flipped from `0` to `1`, 

_However, the limitation of arkworks' approach is that, they won't allow comparison between two variables lies within `[(p-1)/2, p)`._

---

Fortunately, with a little tweak, we can compare any two field elements.

Idea: **either the `a.MSB = 0 AND b.MSB = 1` or the `|p|-1`-least-significant bits of `a` and `b` follow the constraints above.**

We denote $\ell$ as the bit length of $p$, and assume that to be a multiple of three (if not, we pad with zero)

- first decompose $a, b$ as: 
  ```math
  a= (a_0, a_1, \ldots, a_{\ell-1}), b= (b_0, b_1, \ldots, b_{\ell-1})
  ```
- to check $a_0=0 \land b_0 = 1$: constrain $a_0 * (b_0-1) = 0 \land a_0 + (b_0-1) = 0$
- to check the second half of the statement: reuse the second last `acc` value calculated during decomposition in the first step and compute $a', b'$, essentially 
  ```math
  \begin{matrix}
  a'= (a_1, \ldots, a_{\ell-1}) = acc_{a,\, \ell/3 - 1} * 8 + 2 * a_1 + a_2 \\
  b'= (b_1, \ldots, b_{\ell-1}) = acc_{b,\, \ell/3 - 1} * 8 + 2 * b_1 + b_2
  \end{matrix}
  ```
- we are sure both `a', b' < (p-1)/2`, and we enforce the constraints listed in arkworks
- finally we add a `logic_or_gate()` on the above two conditions

Notes:
- our current `decompose_vars_gate()` implementation calculate $acc_i$ from MSB to LSB, but here we require the other way around in order to reuse and not recompute all intermediate values again. 
- additional cost compared to arkworks is ~ 5 more gates.

WDYT? @chancharles92 @mrain

**Comment by chancharles92** [comment]
Generally LGTM, there are some details to be checked more carefully.

`Idea: either the a.MSB = 0 AND b.MSB = 1 or the |p|-1-least-significant bits of a and b follow the constraints above`
We may add one more constraint at the end to distinguish the cases `a.MSB=b.MSB=0` and `a.MSB=b.MSB=1`.

Also we need to be careful with the case that (i) `a.MSB=1, b.MSB=0` **and** (ii) the |p|-1-least-significant bits of a and b follow the constraints above. This still satisfies your predicate, but a < b doesn't hold.

**Comment by mrain** [comment]
My proposed solution for comparison gate between 2 input variables `a` and `b`.

1. Transform it into canonical form of "strictly less than": `a < b`.
    - For strictly greater than, simply swap 2 variables.
    - When equality has to be checked, add a logical negation gate upon it. E.g. `a <= b` to `NOT(b < a)`.
2. Compare both `a` and `b` to `(p-1)/2`. Set `a'=1 iff a <= (p-1)/2 and a'=0 ow`, similarly for `b'`.
    - Check if `a'=0 and b'=1`, constrain `a' * (1 - b') = 0 AND a' + (1 - b') = 0`. 
    - Put constraints to check if `a' = b'` and `(a - b) > (p-1)/2`. When `a` and `b` are both (no) greater than `(p-1)/2`, over `F_p` we have `a < b` if and only if `(a-b) > (p-1)/2`.
 
To complete the solution, we need to implement another gate to compare a variable to a constant `(p-1)/2`. I don't think `range_check` applies here, because it only supports power-of-2 range check. 

@chancharles92 @alxiong WDYT?

**Comment by chancharles92** [comment]
A typo: `a <= b to NOT(b < a)` -> `a <= b to NOT(b > a)`

For point 2, we can discuss a bit more.

**Comment by alxiong** [comment]
> Minor suggestion: a <= b to NOT(b < a) -> a <= b to NOT(a > b)

no need, @mrain 's transformation perfectly fine, cuz you only need to implement `<`, (as for `>`, we just swap operands as suggested)

> we need to implement another gate to compare a variable to a constant (p-1)/2. I don't think range_check applies here, because it only supports power-of-2 range check.

agree, how do you plan to implement `a <= (p-1)/2`?

**Comment by chancharles92** [comment]
`Minor suggestion: a <= b to NOT(b < a) -> a <= b to NOT(a > b)

no need, @mrain 's transformation perfectly fine, cuz you only need to implement <, (as for >, we just swap operands as suggested)`
Oh, it's just meant for readability of the comment, nothing need to change in terms of correctness. Actually I now understand why @mrain uses `NOT(b < a)` because we only have an API for `<`.

**Comment by mrain** [comment]
> agree, how do you plan to implement `a <= (p-1)/2`?

Take the bits representation of `a` and build a binary circuit for it. @alxiong

**Comment by mrain** [comment]
I'm thinking, is it better to use interfaces like `is_le`, `is_geq` rather than `is_cmp(ordering)`?
WDYT @alxiong @chancharles92

**Comment by chancharles92** [comment]
> 

Yes, I think so. It's more understandable.
