### ISSUE TITLE
PLONK for range proofs 

### ISSUE THREAD

**Issue by hamiidreza** [EspressoSystems/jellyfish#92]
I am looking at the Jellyfish library and want to measure the performance of the implemented PLONK for range proof circuits. 
When I run the PLONK prover on the [built-in range circuit](https://github.com/EspressoSystems/jellyfish/blob/706eb8d95162a8e73fce3a39b576fff8075ed660/plonk/src/circuit/customized/mod.rs#L645), I get the error "SnarkError(WrongQuotientPolyDegree(127, 87))" showing the quotient polynomial has wrong degree. Any idea what's the issue? Maybe the culprit is the lack of field conversion (from ScalaField to BaseField) in the range_circuit function?
P.S., here is my code [range.txt](https://github.com/EspressoSystems/jellyfish/files/9252457/range.txt) in the text format. I am testing the code by placing it in the /examples/ directory.

**Comment by chancharles92** [comment]
The SNARK error usually happens if the circuit witness doesn't satisfy the circuit constraints, which is the case in this test:
``let mut rng = ChaCha20Rng::from_seed([0u8; 32]);``
``let x = Fr381::rand(&mut rng);``
``let circuit = range_circuit::<Fr381, Bls12_381>(x)?;``
Here `x` is a random scalar that is larger than 2^10 with high probability, but in the range-circuit function:
``circuit.range_gate(x_var, 10)?;``
It's constrained to be in the range [0, 2^10). 
Hence the circuit won't be satisfied and it's infeasible to obtain a valid proof.

**Comment by chancharles92** [comment]
Changed the error message of "SnarkError(WrongQuotientPolyDegree(127, 87))" in #93 :
`The quotient polynomial has wrong degree: {0}, expected: {1}. Suspect: circuit is not satisfied.` ->
`Suspect: circuit is not satisfied. The quotient polynomial has wrong degree: {0}, expected: {1}.`

**Comment by hamiidreza** [comment]
I also thought that could be the problem; but the error doesn't disappear even when I increase the range interval to say [0, 2^50]!

**Comment by hamiidreza** [comment]
> The SNARK error usually happens if the circuit witness doesn't satisfy the circuit constraints, which is the case in this test: `let mut rng = ChaCha20Rng::from_seed([0u8; 32]);` `let x = Fr381::rand(&mut rng);` `let circuit = range_circuit::<Fr381, Bls12_381>(x)?;` Here `x` is a random scalar that is larger than 2^10 with high probability, but in the range-circuit function: `circuit.range_gate(x_var, 10)?;` It's constrained to be in the range [0, 2^10). Hence the circuit won't be satisfied and it's infeasible to obtain a valid proof.


I also thought that could be the problem; but the error doesn't disappear even when I increase the range interval to say [0, 2^50]!

**Comment by chancharles92** [comment]
> 

A BLS12-381 scalar can be as large as ~2^{254}, can you try to sample an `x` that's smaller than 2^50 and try it again?

**Comment by zhenfeizhang** [comment]
Also if you want to achieve that 1 constraint I mentioned in Discord, you will need ultraplonk
```
    let mut circuit: PlonkCircuit<F> = PlonkCircuit::new_ultra_plonk();
```

**Comment by hamiidreza** [comment]
Perfect! It's indeed working. @zhenfeizhang Thanks. I'm just doing the test for both variants.
Thank you so much for the very quick responses.

**Comment by chancharles92** [comment]
@hamiidreza Is it OK to resolve this issue now?

**Comment by hamiidreza** [comment]
yes, of course.
